imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UtilisateurBundle/Resources/config/services.yml" }
    - { resource: "@EventBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
                    datetime_functions:
                        date:           Oro\ORM\Query\AST\Functions\SimpleFunction
                        time:           Oro\ORM\Query\AST\Functions\SimpleFunction
                        timestamp:      Oro\ORM\Query\AST\Functions\SimpleFunction
                        convert_tz:     Oro\ORM\Query\AST\Functions\DateTime\ConvertTz
                    numeric_functions:
                        timestampdiff:  Oro\ORM\Query\AST\Functions\Numeric\TimestampDiff
                        dayofyear:      Oro\ORM\Query\AST\Functions\SimpleFunction
                        dayofmonth:     Oro\ORM\Query\AST\Functions\SimpleFunction
                        dayofweek:      Oro\ORM\Query\AST\Functions\SimpleFunction
                        week:           Oro\ORM\Query\AST\Functions\SimpleFunction
                        day:            Oro\ORM\Query\AST\Functions\SimpleFunction
                        hour:           Oro\ORM\Query\AST\Functions\SimpleFunction
                        minute:         Oro\ORM\Query\AST\Functions\SimpleFunction
                        month:          Oro\ORM\Query\AST\Functions\SimpleFunction
                        quarter:        Oro\ORM\Query\AST\Functions\SimpleFunction
                        second:         Oro\ORM\Query\AST\Functions\SimpleFunction
                        year:           Oro\ORM\Query\AST\Functions\SimpleFunction
                        sign:           Oro\ORM\Query\AST\Functions\Numeric\Sign
                        pow:            Oro\ORM\Query\AST\Functions\Numeric\Pow
                        round:          Oro\ORM\Query\AST\Functions\Numeric\Round
                    string_functions:
                        md5:            Oro\ORM\Query\AST\Functions\SimpleFunction
                        group_concat:   Oro\ORM\Query\AST\Functions\String\GroupConcat
                        concat_ws:      Oro\ORM\Query\AST\Functions\String\ConcatWs
                        cast:           Oro\ORM\Query\AST\Functions\Cast
                        replace:        Oro\ORM\Query\AST\Functions\String\Replace
                        date_format:    Oro\ORM\Query\AST\Functions\String\DateFormat


# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: UtilisateurBundle\Entity\User
    from_email:
        address: "manai.mohamed.selim@gmail.com"
        sender_name: "selim"

vich_uploader:
    db_driver: orm

    mappings:
        event_affiche:
            uri_prefix: /web/affiches
            upload_destination: '%kernel.project_dir%/web/affiches'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query paameter name
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'     # sliding pagination controls template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template