forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /forum

document:
    resource: "@DocumentBundle/Resources/config/routing.yml"
    prefix:   /

colocation:
    resource: "@ColocationBundle/Resources/config/routing.yml"
    prefix:   /colocation

covoiturage:
    resource: "@CovoiturageBundle/Resources/config/routing.yml"
    prefix:   /covoiturage

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mgilet_notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications
    
event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /event

