event_homepage:
    path:     /events
    defaults: { _controller: EventBundle:Default:index }
ajouter_event:
    path:     /addevent
    defaults: { _controller: EventBundle:Event:ajout }
modifier_event:
    path:     /editevent
    defaults: { _controller: EventBundle:Event:modifier }
lister_event:
    path:     /listevents
    defaults: { _controller: EventBundle:Event:lister }
my_events:
    path:     /myevents
    defaults: { _controller: EventBundle:Event:myEvents }
details_event:
    path:     /details
    defaults: { _controller: EventBundle:Event:details }
data_datatable:
    path:     /data_datatable
    defaults: { _controller: EventBundle:Event:data }
reporter:
    path:     /details
    defaults: { _controller: EventBundle:Event:reporter }
dataAll_datatable:
    path:     /dataAll_datatable
    defaults: { _controller: EventBundle:Event:dataAll }
supprimer_event:
    path:     /supprimer_event
    defaults: { _controller: EventBundle:Event:supprimer }
my_res:
    path:     /mes_reservations
    defaults: { _controller: EventBundle:Event:myRes }
dataRes_datatable:
    path:     /dataRes_datatable
    defaults: { _controller: EventBundle:Event:dataRes }
annuler_res:
    path:     /annuler_reservation
    defaults: { _controller: EventBundle:Event:annulerRes }
confirmer_res:
    path:     /confirmer_reservation
    defaults: { _controller: EventBundle:Event:confirmerRes }


